### PR TITLE
RadioButton/CheckButton and RadioButtonGroup/CheckButtonGroup

### PR DESCRIPTION
**Pull request by OrkhanAlikhanov**
#### RadioButton
```swift
open func setIconColor(_ color: UIColor, for state: UIControlState)
open func iconColor(for state:  UIControlState) -> UIColor
open override var isEnabled: Bool { get set }
open override var isSelected: Bool { get set }
open var isAnimating: Bool { get }
open func setSelected(_ isSelected: Bool, animated: Bool)
```
#### CheckButton
```swift
// ... Same as RadioButton
open var checkmarkColor: UIColor { get set }
```
----
#### RadioButtonGroup
```swift
public convenience init(titles: [String])
public convenience init(buttons: [RadioButton])

open var buttons: [RadioButton] { get set }
open var selectedButton: RadioButton? { get }
open var selectedIndex: Int { get }
```
#### CheckButtonGroup
```swift
public convenience init(titles: [String])
public convenience init(buttons: [CheckButton])

open var buttons: [CheckButton] { get set }
open var selecetedButtons: [CheckButton] { get }
open var selectedIndices: [Int] { get }
```
A quick demo with this [setup code](https://gist.github.com/OrkhanAlikhanov/56bf73baed9a30287ec150ec5fab12e1)
radio demo

### CODE REVIEW

**Comment by OrkhanAlikhanov** [comment]
Let me add docs as well

**Comment by adamdahan** [comment]
@OrkhanAlikhanov What a great job you have done with RadioButton, CheckboxButton, Groups and their internals 👏 

Great use of: 

- CALayers
- High order functions
- Motion
& Grid. 

All of my comments in regard to the implementation would have only been about: 

- Private struct for numbers
- Access control 
- Function signatures 

Let's have a conversation over Gitter and well get this into the next release. 

Thank you for your hard work.

**Comment by OrkhanAlikhanov** [comment]
@adamdahan Thank you for the review, I'll refactor the code according to your suggestions at this weekend inshaAllah

**Comment by Recouse** [comment]
Any news?

**Comment by OrkhanAlikhanov** [comment]
@Recouse If you want the component, drag and drop the files into your project and import Material framework for every file:
```swift
import Material
```

If a file does not compile add `@testable import Material` because I've used some internal things in some files.

**Comment by Recouse** [comment]
@OrkhanAlikhanov Thanks.
But it will be better to see this in Material library.

**Comment by mahdimoqadasi** [comment]
How can I use right to left? (I want to label be on left side)

**Comment by mahdimoqadasi** [comment]
I found it. for anyone has this issue: 
radioItem.semanticContentAttribute = .forceRightToLeft

**Pull request merged**
