### PR TITLE
Realized issue-151

### PR DESCRIPTION
**Pull request by svyatoslav-reshetnikov**

### CODE REVIEW

**Comment by danieldahan** [comment]
Thank you for this. The PR should go to the development branch.

**Comment by svyatoslav-reshetnikov** [comment]
Hi Dan,
Sorry for my oversight. I must to create new PR in development branch or you'll fix it?

**Comment by danieldahan** [comment]
I'll add the changes you made :) thank you. 

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by svyatoslav-reshetnikov** [comment]
Thank you for beautiful library! :)

**Pull request closed without merging**
