### PR TITLE
TextField inset added

### PR DESCRIPTION
**Pull request by slxl**
- Ability to inset textfield's text and placeholder label independently
from leftView and dividerView

### CODE REVIEW

**Comment by danieldahan** [comment]
Nicely done :) Thank you! I am going to review this before Material 2.5 releases, and include this in. The end of the month is the latest release date.

**Comment by danieldahan** [comment]
Hey, adding this in Material 2.5.1. I didn't want to hold Material 2.5.0 any longer. Thanks and this will be in very soon.

**Comment by danieldahan** [comment]
Thank you very much :) !!!!

**Comment by slxl** [comment]
glad to help. thanks for your project as well

**Pull request merged**
