### PR TITLE
Privacy

### PR DESCRIPTION
**Pull request by ConfusedVorlon**
trying again. I think this is how you aim something to development...

### CODE REVIEW

**Comment by danieldahan** [comment]
Perfect! Thank you for this. I will get it out in the next release :) Which is later today.

**Comment by ConfusedVorlon** [comment]
would be great if you could have a look at the extension-safe stuff soon. 
That would let me start using this repo rather than my fork...

**Comment by danieldahan** [comment]
Sounds good, after this release, I will tackle that. So much has been happening with CosmicMind, so thank you for your patience.

**Comment by danieldahan** [comment]
I am going to need to add this to tomorrow's release, 2.2.4. Thank you!

**Comment by ConfusedVorlon** [comment]
excellent - thanks. Just a reminder to tweak the wiki installation page - it doesn't seem to be open for me to edit.

**Comment by danieldahan** [comment]
:) About to do it

**Comment by danieldahan** [comment]
Does it look correct https://github.com/CosmicMind/Material/wiki/Installation ?

**Comment by ConfusedVorlon** [comment]
that works (just tested it)
although you don't need version specifiers on the subspecs.

**Comment by danieldahan** [comment]
I believe you are correct. I was following this example [Subspecs](https://guides.cocoapods.org/syntax/podspec.html#subspec).

**Pull request merged**
