### PR TITLE
Improved navigationBar widget

### PR DESCRIPTION
**Pull request by ramonvic**
Now `navigationBarItem` not need assign `titleLabel` and `detailLabel`, to show those elements, only need set `viewController.title` or `navigationItem.title` and `navigationItem.detail`, related on #313 

Revised to the titleView overlap the `rightControls` on `navigationBar`.

Now title and detail font are setted from `UINavigationBar.appearance().titleTextAttributes`, a new key was added for the `detailLabel` font `NSSecondaryFontAttributeName` related on #277 

I think that's all

### CODE REVIEW

**Comment by danieldahan** [comment]
This looks great. I will go over it in the morning and merge it in.

**Comment by danieldahan** [comment]
@ramonvic Hey, I just realized that this is going to master. Can you send it as a PR to development? Thank you!

**Comment by ramonvic** [comment]
My fault :), i sended to master wrong

**Comment by danieldahan** [comment]
I'll close this and when you get a chance, please send it to development :) Otherwise, I looked it over and it looks great.

**Comment by danieldahan** [comment]
Hey! Sorry I didn't include this before. I am working it into the project now, as it required quite the update. I also revamped the NavigationBar. Once again, thank you!

**Comment by ramonvic** [comment]
No problem, when dev release is done I update my branch :)

**Pull request closed without merging**
