### PR TITLE
CheckBox and RadioButton

### PR DESCRIPTION
**Pull request by OrkhanAlikhanov**
Partial implementation of `CheckBox` and `RadioButton`. Has only state changing animations. None of the classes is marked with `open` access modifier.  Misses a lot and `titleLabel` property.
material

### CODE REVIEW

**Comment by OrkhanAlikhanov** [comment]
Actually it would be better to inherit from `UIButton` I think.

**Comment by danieldahan** [comment]
Amazing! Thank you :)

**Comment by danieldahan** [comment]
This has been added to https://github.com/CosmicMind/Material/tree/wip-checkbox-radiobutton in order to keep the next release clean until this is ready.

**Comment by danieldahan** [comment]
A related PR https://github.com/CosmicMind/Material/pull/878

**Comment by Deminem** [comment]
That's awesome! any plans to integrate this feature in the upcoming release.

However, there are couple of things which I noticed for CheckBox and RadioBox.

Xcode complains on referencing the CheckBox through IBOutlet. I guess it might be just because the CheckBox class not declared as open.

**Comment by danieldahan** [comment]
Hey! There are plans to release these components. Not in the next release though. This is the branch that this should be working on, https://github.com/CosmicMind/Material/tree/wip-checkbox-radiobutton. I am going to rebase this branch and then merge this in :)

**Comment by danieldahan** [comment]
Let's get this in within the next couple releases :)

**Comment by Deminem** [comment]
@danieldahan - Thank for the feedback. Looking forward to it soon ;)

**Pull request merged**
