### PR TITLE
Material - Moved files in xcode structure

### PR DESCRIPTION
**Pull request by vivi7**
This Pull request doesn't add any feature, just move the file in the same folder structure you can find in xcode project

### CODE REVIEW

**Comment by vivi7** [comment]
I'm starting to use this lib for work so we can create other pull requests to contribute new features

**Comment by OrkhanAlikhanov** [comment]
This is great @vivi7. I always wanted to have them in sync. I don't know what @danieldahan thinks on this matter. Also, can you update the PR against `development` branch?

**Comment by danieldahan** [comment]
Thank you for sending this to us. All PRs must be against `development`. As you can see, conflicts arise. We would be happy to get an updated version of this PR for review against the `development` branch.

**Comment by vivi7** [comment]
> This is great @vivi7. I always wanted to have them in sync. I don't know what @danieldahan thinks on this matter. Also, can you update the PR against `development` branch?

Sure, I'm sorry, I just made mistake about branches

**Pull request closed without merging**
