### PR TITLE
Added left and right image views offset to placeholder frame

### PR DESCRIPTION
**Pull request by hastoukopsaro**

### CODE REVIEW

**Comment by danieldahan** [comment]
Hey! Thank you for the PR :) Can you show me a demo of what this does please? Thank you!

**Comment by hastoukopsaro** [comment]
It allows for a user to overlay a left Image (and/or a right button i.e. show password icon) over the text field.

Here's a GIF of the said functionallity
left_image

**Comment by OrkhanAlikhanov** [comment]
Can't this behavior be achieved through setting `UIImageView` to `leftView` and `rightView`?:
```swift
textField.leftView = UIImageView(image: Icon.favorite)
textField.rightView = UIImageView(image: Icon.favorite)
```

**Comment by OrkhanAlikhanov** [comment]
Oh, I noticed now, the icon in your image is above the line, as you mentioned. One question, how does it behave during placeholder animation?

**Comment by danieldahan** [comment]
As @OrkhanAlikhanov mentioned, there is support for left / right views. Is there a benefit to your setup over the already provided left / right views?

**Comment by hastoukopsaro** [comment]
@danieldahan There is no benefit per se... it's just not the same. By effectively offsetting the placeholder, one can overlay a UIView and make it appear to be inside the TextField (above the line).

**Comment by danieldahan** [comment]
@hastoukopsaro You can do that as well by adjusting the divider line, and extending it across the entire TextField. I am going to leave this PR up and take a look at it more closely in the upcoming week.

**Comment by danieldahan** [comment]
I am going to close this PR as it is already possible to accomplish the proposed behavior. Thank you very much for sending this our way :) !!!

**Pull request closed without merging**
