### PR TITLE
Should always trigger TabBar Delegate

### PR DESCRIPTION
**Pull request by autumnssun**
Problem: when swipe TabsControllerDelegate not trigger.
TabsControllerDelegate Only trigger when taps on TabBarItems

Solution remove the check isTriggeredByUserInteraction
to call the delegate

tabsController?(tabsController: s, didSelect: viewController)

### CODE REVIEW

**Comment by autumnssun** [comment]
@OrkhanAlikhanov sorry, it looks like I made a little mistake here. I didn’t mean to push these commits: 3e9b9fe and to comicmind/master I was just pushing these to use on my project. 
However I have been experimenting with different fixes. And I think calling the delegate in the select(at:index) after the transition has finished would be better, what do you think. 

We can close this PR then I rebase this to dev branch and send the push again. Shall we do this?

**Comment by OrkhanAlikhanov** [comment]
That's true, `handleSwipeGesture()` calls `select(at:index)`. 
https://github.com/autumnssun/Material/blob/955cec565892d7b3b14c7dc84cfccf3b31c4ca1a/Sources/iOS/TabsController.swift#L380-L386

So, we need to change `select(at:index)` signature to decide whether it should fire delegate methods or not. @danieldahan  What do you think?  Should't `select()` fire delegate methods by default? Or we should add option to fire that? Which guide should we follow?

@autumnssun Actually there is no need to close and recreate PR, you can reset all the commits and do one-clean commit if you want. But I think we can keep this as well since commit history does not bother @danieldahan as it bothers me, lol.

**Comment by autumnssun** [comment]
I also notice something:
As I tried to override this function: and calling it’s super. 
So that I can pass in a new completion in the function so that it can be called after the transition finished. I put a break there, but it didn’t break. 


  `open override func transition(to viewController: UIViewController, completion: ((Bool) -> Void)?) {
    transition(to: viewController, isTriggeredByUserInteraction: false, completion: completion)
  }`

This might link to this issue too. 
https://github.com/CosmicMind/Material/issues/1081

**Comment by danieldahan** [comment]
@autumnssun Interesting. I will replicate this and see what I can find. Thank you!

**Comment by danieldahan** [comment]
Let's follow https://github.com/CosmicMind/Material/issues/1056 for this. I believe it is the same issue.

**Comment by danieldahan** [comment]
@OrkhanAlikhanov in the `select(index)` function, it calls `animate(to: tabItems[index], isTriggeredByUserInteraction: false, completion: completion)` which has the flag to determine if the delegate should be fired or not.

**Pull request closed without merging**
