### PR TITLE
Upgrade to Swift 4

### PR DESCRIPTION
**Pull request by jeffaburt**
This PR upgrades the source code to support Swift 4.

Note: I decided to remove `CharacterAttribute` completely due to the addition of `NSAttributedStringKey`. If you'd prefer me to deprecate this instead, please let me know.

After merging this PR, please create a `3.0.0` tag:

```
cd Material/
git checkout master
git pull origin master
git tag 3.0.0
git push origin 3.0.0
```

Then, send an update to CocoaPods, that way we can just run `pod update Material` and get all of the Swift 4 goodies:

```
pod trunk push
```

Also, be sure to update the [Installation Guide](https://github.com/CosmicMind/Material/wiki/Installation) to mention the new version.

Thanks!

### CODE REVIEW

**Comment by danieldahan** [comment]
I literally just pushed an update to Swift 4 to the development branch. I will still review this and see if there is anything I can merge in. Thanks for the PR :)

**Comment by jeffaburt** [comment]
Ahhhh I totally missed the `development` branch. Now I'm sad. Thanks for all of your hard work!

**Comment by danieldahan** [comment]
Thanks buddy :) I truly appreciate the PR.

**Comment by jeffaburt** [comment]
I'll go ahead and close this but leave the branch open in case you want to pull anything from it! Thanks again!

**Comment by danieldahan** [comment]
Great! Thank you.

**Pull request closed without merging**
