### PR TITLE
TextView class now adheres to Material guidelines

### PR DESCRIPTION
**Pull request by cody1024d**
@danieldahan 

I have added functionality to the TextView to give it a detail label, a divider, as well as a correctly animating placeholder.  The goal here was to make the textview function similar to the textfield, as well as the Material Guidelines for a multi-line field.

I know the TextView is missing some customizable capabilities that the Textfield had, but, to be honest, they were kept out because I didn't need them for my particular use case of this ui element.  

Let me know what you think!

### CODE REVIEW

**Comment by cody1024d** [comment]
@danieldahan  I've resolved the merge issues seemingly as they should be; let me know if anymore work needs to be done to this

**Comment by danieldahan** [comment]
Excellent, thank you! I am going to give this a thorough look through soon. I have been working on a documentation portal for the past couple weeks. This is on the queue and thank you!

**Comment by madasamys** [comment]
Our team will waiting for this feature. @danieldahan  When will you going to merge this and release this?

**Comment by danieldahan** [comment]
I will review it over the weekend :) @madasamys I am now fully focused on Material 3 and adding in the new features.

**Comment by adamdahan** [comment]
@cody1024d Will be testing this later this afternoon. Will be following up with acceptance. Thank you for the contribution.

**Comment by adamdahan** [comment]
Hi @cody1024d 😄  

I was wondering if you could provide a sample zip project that I could use to test some edge cases? 

Once I give it a run I am happy to go through the code more thoroughly and help accelerate your contributions adoption in the next release. 

Best!

**Comment by cody1024d** [comment]
@adamdahan Unfortunately I won't be able to do this any time soon; as I have some RL stuff I've got to take care of this week that's going to leave me with very little free time.  I know it will only take 15 minutes, so if I find the time, I will, but I cannot promise it.

You *should* be able to just update the example project that comes with Material, and just switch in a TextView, though.

**Comment by danieldahan** [comment]
There is a new PR to add this feature that is up to date. I am going to close this. Thank you for submitting this PR! https://github.com/CosmicMind/Material/pull/1130

**Pull request closed without merging**
