### PR TITLE
Added custom placeholderPadding and detailDistance

### PR DESCRIPTION
**Pull request by aleufms**
Added custom placeholder padding and custom detail Distance to divider. The default values is to high for me.

### CODE REVIEW

**Comment by danieldahan** [comment]
Thank you for this. I am going to look at it over the weekend before the next release.

**Comment by danieldahan** [comment]
This looks good I will accept it once I am ready to test, before the next release. Thank you!

**Comment by aleufms** [comment]
Ok, feel free to rename the variables and update the documentation. I am not good with variables names and English as well. ;)

**Comment by danieldahan** [comment]
I just realized this is PR to master. Would you be able to send this to development please? Thank you!

**Comment by danieldahan** [comment]
I am going to take the changes you made, and place them into development. In general, I would like for you to be seen as the contributor, which means you must send the PR to development. So next time, please do so :)

**Pull request closed without merging**
