### PR TITLE
Storyboard hot fixes

### PR DESCRIPTION
**Pull request by OrkhanAlikhanov**
Should fix issues: #1229 and #1230

### CODE REVIEW

**Comment by mohpor** [comment]
@OrkhanAlikhanov by the looks of it, it might solve my issues, but I think it will break others' !

**Comment by OrkhanAlikhanov** [comment]
@mohpor How would it?

**Comment by mohpor** [comment]
those who rely on placeholder color as tint (like what I've done) will see changes.

But I guess it might be ok if it fixes a problem.

**Comment by OrkhanAlikhanov** [comment]
I don't think so. Updating `placeholderActiveColor` still updates `tintColor`. However, unlike previous code, this time updated `tintColor` will not be overridden unless `placeholderActiveColor` is updated.

**Comment by mohpor** [comment]
I've checked a few places, and I couldn't see any problems.

thanks

**Comment by danieldahan** [comment]
@mohpor please reference the `development` branch for this hot-fix, and tomorrow I will make a release. Thank you @OrkhanAlikhanov, nice work!

**Comment by mohpor** [comment]
@danieldahan 
It's OK, I'd rather wait for the release. 

Thanks

**Pull request merged**
