### PR TITLE
added ShouldOpen and ShouldClose delegate methods to FABMenuDelegate

### PR DESCRIPTION
**Pull request by mjurenka**
i have added these methods as discussed in https://github.com/CosmicMind/Material/issues/1043

### CODE REVIEW

**Comment by danieldahan** [comment]
Thank you! Will take a look very soon.

**Comment by OrkhanAlikhanov** [comment]
@danieldahan It seems this PR causes not to compile? Can you verify please?

**Comment by OrkhanAlikhanov** [comment]
https://github.com/CosmicMind/Material/pull/1046/commits/f22face7bf6686ec289df46d5b8c1d34e1cc03d4 is totally fine, something had to do with merge. I review both (@mjurenka's and GitHub's merge) commits  and they seem okay. But the changes shown in [Files Changed](https://github.com/CosmicMind/Material/pull/1046/files) tab it does not reflect the 2 commits in this PR. it looks really weird and causes compilation error.

**Comment by danieldahan** [comment]
@OrkhanAlikhanov I think that happened when I fixed the merge conflicts. I may have removed the incorrect parts. We can roll this commit back and remerge, or take the necessary changes and make them ourselves to speed it up. What would you like to do?

**Comment by OrkhanAlikhanov** [comment]
I would go with the second option. Making changes ourselves. I can make a PR for that if you agree.

**Comment by danieldahan** [comment]
Agreed and good choice. Thank you!

**Pull request merged**
