### PR TITLE
Define enumerations for animation

### PR DESCRIPTION
**Pull request by shoheiyokoyama**
Hi :smiley:
I define 2 enumeration for animation.

### `AnimationTimingFunction`
`kCA-prefix` isn't suitable for Swift-Style.
so I define `AnimationTimingFunction`. please use `AnimationTimingFunctionToValue()` with `AnimationTimingFunction` like as `AnimationFillModeToValue()`.

### `AnimationKey`
I define `convenience initializer` with `AnimationKey` in `CABasicAnimation`.
enabled to initialize very easily, safely.

### CODE REVIEW

**Comment by danieldahan** [comment]
Nice, I will take a look at this tomorrow :) Thank you!

**Comment by danieldahan** [comment]
Oh, and can you please send this to `development` ? Thank you!

**Comment by shoheiyokoyama** [comment]
ok! i'm going to request to `development`

**Comment by danieldahan** [comment]
I merged your other PR :) Thank you!

**Pull request closed without merging**
