### PR TITLE
Allow option to be extension safe

### PR DESCRIPTION
**Pull request by ConfusedVorlon**
users can disable some functionality in order to be extension-safe

### CODE REVIEW

**Comment by ConfusedVorlon** [comment]
this handles issue #488 (and I also need it myself!)

**Comment by danieldahan** [comment]
Thank you for this. I'll take a look at this within the next couple days. I have a few other things in the queue right now.

**Comment by ConfusedVorlon** [comment]
Any thoughts on this? I'm going to be submitting a build as soon as the iOS 10 gm comes out which should be soon. It would be nice to not have to update my fork!

**Comment by ddahan-imvu** [comment]
What will most likely happen is I will take the ideas you presented and work it into the framework in a way going forward that allows this type of configuration.

**Comment by danieldahan** [comment]
What will most likely happen is I will take the ideas you presented and work it into the framework in a way going forward that allows this type of configuration.

**Comment by ConfusedVorlon** [comment]
looks like a relevant blog post here - might be helpful
https://miqu.me/blog/2016/11/28/app-extensions-xcode-and-cocoapods-omg/

**Comment by danieldahan** [comment]
Nice, I will read it through.

**Comment by danieldahan** [comment]
Let's tackle this latest by Monday :) I will review it this week and read the article. Thanks for your patience.

**Comment by ConfusedVorlon** [comment]
thanks for getting to this - you do fantastic work on this whole project :)

**Comment by danieldahan** [comment]
Thank you :)

**Comment by danieldahan** [comment]
Sadly this fell so far behind. I am sorry I never got around to including it. At this point, I will need to look into this issue from scratch. Thank you.

**Pull request closed without merging**
